# Generated by Django 3.2 on 2021-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('Businessname', models.CharField(max_length=100)),
                ('Person_name', models.CharField(blank=True, max_length=100)),
                ('contact', models.IntegerField()),
                ('verifiedstatus', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
