# Generated by Django 3.2 on 2021-06-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen_cylinder_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Person_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
